"""Write a small hand-made sample dataset to public/data/recipes.json.

Stand-in while the Food.com data is unavailable; the output schema is identical
to build_recipes.py. All recipes here are original, simple house recipes.
"""
from pathlib import Path
from taxonomy import infer_diets, infer_main, infer_difficulty
from dataset_io import write_dataset

SRC = {"name": "Cooking Hub sample recipe"}


def R(title, cuisine, minutes, meals, vibes, servings, ings, steps, rating=4.5):
    names = [n for n, _ in ings]
    return {
        "id": "s-" + title.lower().replace(" ", "-"),
        "title": title, "cuisine": cuisine, "minutes": minutes,
        "difficulty": infer_difficulty(minutes, len(steps), len(ings)),
        "meals": meals, "vibes": vibes, "diets": infer_diets(names),
        "main": infer_main(names), "servings": servings, "rating": rating,
        "ingredients": [{"name": n, "text": t} for n, t in ings],
        "steps": steps, "source": SRC,
    }


WK, DATE, LUNCH, BED, COZY, FRESH = "weeknight", "date-night", "workday-lunch", "breakfast-in-bed", "comfort-food", "light-and-fresh"

RECIPES = [
    R("Buckwheat Pancakes", "american", 25, ["breakfast"], [BED, "sunday-morning"], 4,
      [("buckwheat flour", "1 cup buckwheat flour"), ("flour", "1/2 cup all-purpose flour"), ("baking powder", "2 tsp baking powder"),
       ("milk", "1 1/4 cups milk"), ("egg", "1 egg"), ("butter", "2 tbsp melted butter"), ("maple syrup", "maple syrup, to serve"), ("salt", "1/4 tsp salt")],
      ["Whisk both flours, baking powder and salt.", "Beat in milk, egg and melted butter until just combined; rest 5 minutes.",
       "Cook 1/4-cup scoops on a buttered pan over medium heat, 2 minutes per side.", "Serve stacked with maple syrup."]),
    R("Fluffy Scrambled Eggs on Toast", "american", 10, ["breakfast"], [BED, WK], 2,
      [("egg", "4 eggs"), ("butter", "1 tbsp butter"), ("milk", "2 tbsp milk"), ("bread", "2 slices bread"), ("salt", "pinch of salt"), ("black pepper", "black pepper")],
      ["Whisk eggs with milk and salt.", "Melt butter over low heat, add eggs and stir slowly until softly set.", "Toast bread and spoon eggs on top."]),
    R("Banana Oat Pancakes", "american", 20, ["breakfast"], [BED, "sunday-morning"], 2,
      [("banana", "2 ripe bananas"), ("oats", "1 cup rolled oats"), ("egg", "2 eggs"), ("cinnamon", "1/2 tsp cinnamon"), ("butter", "butter for the pan")],
      ["Blend bananas, oats, eggs and cinnamon into a thick batter.", "Cook small rounds in a buttered pan 2 minutes per side."], 4.3),
    R("Overnight Oats with Berries", "american", 5, ["breakfast"], [WK, FRESH, "meal-prep"], 1,
      [("oats", "1/2 cup rolled oats"), ("yogurt", "1/3 cup yogurt"), ("milk", "1/2 cup milk"), ("honey", "1 tsp honey"), ("strawberry", "handful of strawberries")],
      ["Stir oats, yogurt, milk and honey in a jar.", "Chill overnight, then top with sliced strawberries."], 4.2),
    R("French Toast", "french", 20, ["breakfast"], [BED, "sunday-morning"], 2,
      [("bread", "4 thick slices bread"), ("egg", "2 eggs"), ("milk", "1/2 cup milk"), ("cinnamon", "1/2 tsp cinnamon"), ("vanilla", "1 tsp vanilla"), ("butter", "butter for the pan"), ("maple syrup", "maple syrup")],
      ["Whisk eggs, milk, cinnamon and vanilla in a shallow dish.", "Soak bread slices 20 seconds per side.", "Fry in butter until golden on both sides; serve with syrup."], 4.6),
    R("Spaghetti Aglio e Olio", "italian", 20, ["dinner"], [WK, DATE], 2,
      [("spaghetti", "200 g spaghetti"), ("garlic", "5 cloves garlic, sliced"), ("olive oil", "1/3 cup olive oil"), ("chili flakes", "1/2 tsp chili flakes"), ("parsley", "handful of parsley"), ("salt", "salt")],
      ["Boil spaghetti in salted water until al dente; reserve a cup of pasta water.", "Gently warm garlic in olive oil until pale gold.", "Toss pasta with the oil, chili and a splash of pasta water.", "Finish with parsley."], 4.6),
    R("Tomato Basil Pasta", "italian", 25, ["dinner"], [WK, "crowd-pleaser"], 3,
      [("pasta", "250 g pasta"), ("canned tomatoes", "1 can (400 g) crushed tomatoes"), ("garlic", "2 cloves garlic"), ("basil", "fresh basil"), ("olive oil", "2 tbsp olive oil"), ("parmesan", "grated parmesan"), ("salt", "salt")],
      ["Cook pasta in salted water.", "Sauté garlic in oil, add tomatoes and simmer 10 minutes.", "Toss with pasta, torn basil and parmesan."], 4.4),
    R("Creamy Mushroom Risotto", "italian", 50, ["dinner"], [DATE, COZY], 3,
      [("arborio rice", "1 cup arborio rice"), ("mushroom", "250 g mushrooms, sliced"), ("onion", "1 small onion"), ("garlic", "2 cloves garlic"), ("vegetable broth", "4 cups warm vegetable broth"), ("butter", "2 tbsp butter"), ("parmesan", "1/2 cup parmesan"), ("white wine", "1/2 cup white wine")],
      ["Brown mushrooms in butter; set aside.", "Soften onion and garlic, toast the rice 1 minute, add wine.", "Add warm broth a ladle at a time, stirring, for about 25 minutes.", "Fold in mushrooms, parmesan and a knob of butter."], 4.7),
    R("Margherita Flatbread", "italian", 30, ["dinner", "lunch"], [DATE, "crowd-pleaser"], 2,
      [("flatbread", "2 flatbreads"), ("canned tomatoes", "1/2 cup crushed tomatoes"), ("mozzarella", "150 g fresh mozzarella"), ("basil", "fresh basil"), ("olive oil", "drizzle of olive oil")],
      ["Heat oven to 230 C.", "Spread tomatoes on flatbreads, top with torn mozzarella.", "Bake 8-10 minutes until bubbling; finish with basil and oil."], 4.3),
    R("Lemon Garlic Chicken", "american", 35, ["dinner"], [WK, DATE], 3,
      [("chicken breast", "3 chicken breasts"), ("lemon", "1 lemon"), ("garlic", "4 cloves garlic"), ("olive oil", "2 tbsp olive oil"), ("butter", "1 tbsp butter"), ("parsley", "chopped parsley"), ("salt", "salt"), ("black pepper", "pepper")],
      ["Season chicken and sear in oil 5 minutes per side.", "Add butter, garlic and lemon juice; spoon over chicken until cooked through.", "Garnish with parsley."], 4.5),
    R("Chicken Fried Rice", "chinese", 25, ["dinner", "lunch"], [WK, "leftovers-friendly"], 3,
      [("rice", "3 cups cooked rice, cold"), ("chicken breast", "1 chicken breast, diced"), ("egg", "2 eggs"), ("carrot", "1 carrot, diced"), ("green onion", "3 green onions"), ("soy sauce", "3 tbsp soy sauce"), ("sesame oil", "1 tsp sesame oil"), ("vegetable oil", "2 tbsp vegetable oil")],
      ["Stir-fry chicken in oil until cooked; push aside.", "Scramble the eggs in the same pan.", "Add carrot and rice, tossing on high heat 4 minutes.", "Season with soy sauce and sesame oil; top with green onion."], 4.4),
    R("Garlic Ginger Broccoli Stir-Fry", "chinese", 15, ["dinner", "side"], [WK, FRESH], 2,
      [("broccoli", "1 large head broccoli"), ("garlic", "3 cloves garlic"), ("ginger", "1 tbsp grated ginger"), ("soy sauce", "2 tbsp soy sauce"), ("sesame oil", "1 tsp sesame oil"), ("vegetable oil", "1 tbsp vegetable oil")],
      ["Stir-fry broccoli in hot oil 3 minutes.", "Add garlic and ginger for 30 seconds.", "Splash in soy sauce and sesame oil; serve over rice."], 4.2),
    R("Teriyaki Salmon", "japanese", 25, ["dinner"], [DATE, WK], 2,
      [("salmon", "2 salmon fillets"), ("soy sauce", "3 tbsp soy sauce"), ("honey", "2 tbsp honey"), ("garlic", "1 clove garlic"), ("ginger", "1 tsp grated ginger"), ("rice", "rice, to serve")],
      ["Simmer soy sauce, honey, garlic and ginger until syrupy.", "Sear salmon skin-side down 4 minutes, flip 2 minutes.", "Glaze with sauce and serve over rice."], 4.6),
    R("Black Bean Tacos", "mexican", 20, ["dinner", "lunch"], [WK, "crowd-pleaser"], 3,
      [("black beans", "1 can black beans"), ("tortilla", "6 small tortillas"), ("avocado", "1 avocado"), ("lime", "1 lime"), ("cilantro", "cilantro"), ("cumin", "1 tsp cumin"), ("onion", "1/2 red onion")],
      ["Warm beans with cumin and a splash of water, mashing lightly.", "Warm the tortillas.", "Fill with beans, sliced avocado, onion, cilantro and lime."], 4.3),
    R("Chicken Quesadillas", "mexican", 20, ["dinner", "lunch"], [WK, "crowd-pleaser"], 2,
      [("tortilla", "4 tortillas"), ("cheddar", "1 1/2 cups shredded cheddar"), ("chicken breast", "1 cooked chicken breast, shredded"), ("bell pepper", "1 bell pepper, sliced")],
      ["Layer cheese, chicken and pepper on half of each tortilla and fold.", "Toast in a dry pan 2-3 minutes per side until crisp and melted."], 4.2),
    R("Guacamole and Chips", "mexican", 10, ["snack"], ["game-night", FRESH], 4,
      [("avocado", "3 ripe avocados"), ("lime", "1 lime"), ("onion", "1/4 red onion"), ("cilantro", "cilantro"), ("salt", "salt"), ("tortilla chips", "tortilla chips, to serve")],
      ["Mash avocados with lime juice and salt.", "Stir in finely diced onion and cilantro.", "Serve right away with chips."], 4.5),
    R("Chickpea Curry", "indian", 30, ["dinner"], [WK, COZY], 3,
      [("chickpeas", "2 cans chickpeas"), ("coconut milk", "1 can coconut milk"), ("canned tomatoes", "1 cup crushed tomatoes"), ("onion", "1 onion"), ("garlic", "3 cloves garlic"), ("ginger", "1 tbsp grated ginger"), ("curry powder", "2 tbsp curry powder"), ("spinach", "2 handfuls spinach"), ("vegetable oil", "1 tbsp oil")],
      ["Soften onion in oil, add garlic, ginger and curry powder for 1 minute.", "Add tomatoes, coconut milk and chickpeas; simmer 15 minutes.", "Stir in spinach until wilted; serve with rice."], 4.6),
    R("Red Lentil Soup", "middle-eastern", 35, ["dinner", "soup"], [COZY, "meal-prep"], 4,
      [("red lentils", "1 cup red lentils"), ("onion", "1 onion"), ("carrot", "2 carrots"), ("garlic", "3 cloves garlic"), ("cumin", "1 tsp cumin"), ("vegetable broth", "4 cups vegetable broth"), ("lemon", "1 lemon"), ("olive oil", "2 tbsp olive oil")],
      ["Soften onion, carrot and garlic in oil; stir in cumin.", "Add lentils and broth; simmer 20 minutes until soft.", "Blend part of the soup and finish with lemon juice."], 4.5),
    R("Greek Salad", "greek", 10, ["lunch", "salad", "side"], [LUNCH, FRESH], 2,
      [("cucumber", "1 cucumber"), ("tomato", "3 tomatoes"), ("red onion", "1/2 red onion"), ("feta", "100 g feta"), ("olives", "handful of olives"), ("olive oil", "3 tbsp olive oil"), ("red wine vinegar", "1 tbsp red wine vinegar")],
      ["Chop cucumber, tomato and onion into chunks.", "Toss with olives, oil and vinegar; crumble feta on top."], 4.4),
    R("Avocado Toast with Egg", "american", 10, ["breakfast", "lunch"], [LUNCH, BED], 1,
      [("bread", "2 slices bread"), ("avocado", "1 avocado"), ("egg", "2 eggs"), ("lemon", "squeeze of lemon"), ("chili flakes", "pinch of chili flakes"), ("salt", "salt")],
      ["Toast bread; mash avocado with lemon and salt.", "Fry or poach the eggs.", "Pile avocado on toast, top with egg and chili flakes."], 4.3),
    R("Tuna Salad Sandwich", "american", 10, ["lunch"], [LUNCH], 2,
      [("tuna", "1 can tuna"), ("mayonnaise", "2 tbsp mayonnaise"), ("celery", "1 stalk celery"), ("lemon", "squeeze of lemon"), ("bread", "4 slices bread")],
      ["Flake tuna and mix with mayonnaise, diced celery and lemon.", "Spread onto bread and slice."], 4.0),
    R("Caprese Sandwich", "italian", 10, ["lunch"], [LUNCH, FRESH], 1,
      [("bread", "1 ciabatta roll"), ("mozzarella", "100 g mozzarella"), ("tomato", "1 tomato"), ("basil", "fresh basil"), ("olive oil", "drizzle of olive oil")],
      ["Slice the roll and layer mozzarella, tomato and basil.", "Drizzle with oil and season."], 4.4),
    R("Classic Grilled Cheese", "american", 10, ["lunch", "dinner"], [LUNCH, COZY], 1,
      [("bread", "2 slices bread"), ("cheddar", "3 slices cheddar"), ("butter", "1 tbsp butter")],
      ["Butter the outsides of the bread; fill with cheddar.", "Cook in a skillet over medium-low heat until golden and melted, 3 minutes per side."], 4.5),
    R("Baked Potato Soup", "american", 40, ["dinner", "soup"], [COZY], 4,
      [("potato", "4 large potatoes, cubed"), ("onion", "1 onion"), ("garlic", "2 cloves garlic"), ("chicken broth", "4 cups chicken broth"), ("cream", "1/2 cup cream"), ("cheddar", "shredded cheddar"), ("bacon", "4 slices bacon"), ("butter", "2 tbsp butter")],
      ["Crisp the bacon; crumble and set aside.", "Soften onion and garlic in butter, add potatoes and broth; simmer 20 minutes.", "Mash partially, stir in cream; top with cheddar and bacon."], 4.5),
    R("Classic Beef Chili", "american", 60, ["dinner", "soup"], [COZY, "crowd-pleaser", "meal-prep"], 6,
      [("ground beef", "500 g ground beef"), ("kidney beans", "1 can kidney beans"), ("canned tomatoes", "1 can crushed tomatoes"), ("onion", "1 onion"), ("garlic", "3 cloves garlic"), ("chili powder", "2 tbsp chili powder"), ("cumin", "1 tsp cumin")],
      ["Brown beef with onion and garlic.", "Add spices, tomatoes and beans.", "Simmer 40 minutes, stirring occasionally."], 4.6),
    R("Spaghetti Bolognese", "italian", 55, ["dinner"], [COZY, "crowd-pleaser"], 4,
      [("spaghetti", "400 g spaghetti"), ("ground beef", "500 g ground beef"), ("onion", "1 onion"), ("carrot", "1 carrot"), ("garlic", "2 cloves garlic"), ("canned tomatoes", "1 can crushed tomatoes"), ("parmesan", "parmesan, to serve"), ("olive oil", "2 tbsp olive oil")],
      ["Soften finely chopped onion, carrot and garlic in oil.", "Brown the beef, add tomatoes and simmer 30 minutes.", "Serve over cooked spaghetti with parmesan."], 4.5),
    R("Sheet-Pan Sausage and Potatoes", "american", 40, ["dinner"], [WK, "low-effort"], 3,
      [("sausage", "4 sausages"), ("potato", "500 g baby potatoes"), ("bell pepper", "2 bell peppers"), ("onion", "1 onion"), ("olive oil", "3 tbsp olive oil")],
      ["Toss chopped potatoes, peppers, onion and sausage with oil on a tray.", "Roast at 220 C for 30 minutes, turning once."], 4.3),
    R("Shakshuka", "middle-eastern", 30, ["breakfast", "dinner"], [BED, DATE, "sunday-morning"], 2,
      [("egg", "4 eggs"), ("canned tomatoes", "1 can crushed tomatoes"), ("bell pepper", "1 bell pepper"), ("onion", "1 onion"), ("garlic", "2 cloves garlic"), ("cumin", "1 tsp cumin"), ("paprika", "1 tsp paprika"), ("olive oil", "2 tbsp olive oil")],
      ["Soften onion and pepper in oil; add garlic and spices.", "Add tomatoes and simmer 10 minutes.", "Make wells, crack in eggs, cover and cook until set."], 4.7),
    R("Tomato Soup", "american", 30, ["lunch", "soup"], [COZY, LUNCH], 3,
      [("canned tomatoes", "1 large can tomatoes"), ("onion", "1 onion"), ("garlic", "2 cloves garlic"), ("vegetable broth", "2 cups vegetable broth"), ("cream", "1/4 cup cream"), ("butter", "2 tbsp butter")],
      ["Soften onion and garlic in butter.", "Add tomatoes and broth; simmer 15 minutes.", "Blend smooth, stir in cream."], 4.4),
    R("Garlic Butter Shrimp", "american", 15, ["dinner"], [DATE, WK], 2,
      [("shrimp", "300 g shrimp"), ("butter", "3 tbsp butter"), ("garlic", "4 cloves garlic"), ("lemon", "1 lemon"), ("parsley", "chopped parsley"), ("chili flakes", "pinch of chili flakes")],
      ["Melt butter, cook garlic 30 seconds.", "Add shrimp, cook 2 minutes per side.", "Finish with lemon juice and parsley."], 4.6),
    R("Chocolate Chip Cookies", "american", 30, ["dessert"], ["baking-day", "crowd-pleaser"], 12,
      [("flour", "2 1/4 cups flour"), ("butter", "1 cup soft butter"), ("sugar", "1/2 cup sugar"), ("brown sugar", "3/4 cup brown sugar"), ("egg", "2 eggs"), ("vanilla", "2 tsp vanilla"), ("baking soda", "1 tsp baking soda"), ("chocolate chips", "2 cups chocolate chips"), ("salt", "1 tsp salt")],
      ["Cream butter and both sugars; beat in eggs and vanilla.", "Mix in flour, baking soda and salt, then chocolate chips.", "Bake spoonfuls at 180 C for 10-12 minutes."], 4.8),
    R("Chocolate Mug Cake", "american", 5, ["dessert"], ["late-night", "low-effort"], 1,
      [("flour", "4 tbsp flour"), ("sugar", "3 tbsp sugar"), ("cocoa powder", "2 tbsp cocoa powder"), ("milk", "3 tbsp milk"), ("vegetable oil", "2 tbsp oil"), ("chocolate chips", "a few chocolate chips")],
      ["Stir everything in a large mug.", "Microwave 70-90 seconds until just set."], 4.0),
    R("Berry Yogurt Parfait", "american", 5, ["breakfast", "dessert"], [BED, FRESH], 1,
      [("yogurt", "1 cup yogurt"), ("strawberry", "1/2 cup strawberries"), ("honey", "1 tsp honey"), ("oats", "2 tbsp toasted oats")],
      ["Layer yogurt, berries and oats in a glass; drizzle with honey."], 4.2),
    R("Vegan Tofu Scramble", "american", 15, ["breakfast"], [BED, WK], 2,
      [("tofu", "1 block firm tofu"), ("onion", "1/2 onion"), ("spinach", "handful of spinach"), ("turmeric", "1/2 tsp turmeric"), ("olive oil", "1 tbsp olive oil"), ("salt", "salt")],
      ["Soften onion in oil; crumble in tofu with turmeric and salt.", "Cook 6 minutes, stir in spinach until wilted."], 4.1),
    R("Peanut Noodles", "chinese", 15, ["dinner", "lunch"], [WK, LUNCH], 2,
      [("noodles", "200 g noodles"), ("peanut butter", "3 tbsp peanut butter"), ("soy sauce", "2 tbsp soy sauce"), ("lime", "1 lime"), ("garlic", "1 clove garlic"), ("green onion", "2 green onions"), ("honey", "1 tsp honey")],
      ["Cook the noodles and drain.", "Whisk peanut butter, soy sauce, lime, garlic and honey with a splash of warm water.", "Toss with noodles and top with green onion."], 4.4),
    R("Roasted Vegetable Bowl", "american", 40, ["dinner", "lunch"], [FRESH, "meal-prep"], 2,
      [("sweet potato", "1 sweet potato"), ("chickpeas", "1 can chickpeas"), ("broccoli", "1 head broccoli"), ("olive oil", "2 tbsp olive oil"), ("lemon", "1 lemon"), ("rice", "cooked rice or quinoa")],
      ["Roast cubed sweet potato, chickpeas and broccoli with oil at 210 C for 25 minutes.", "Serve over rice with a squeeze of lemon."], 4.3),
    R("Honey Garlic Chicken Thighs", "american", 45, ["dinner"], [WK, COZY], 4,
      [("chicken thigh", "6 chicken thighs"), ("honey", "3 tbsp honey"), ("soy sauce", "3 tbsp soy sauce"), ("garlic", "4 cloves garlic"), ("vegetable oil", "1 tbsp oil")],
      ["Brown the thighs skin-side down.", "Mix honey, soy sauce and garlic; pour over.", "Bake at 200 C for 25 minutes, basting once."], 4.6),
    R("Mushroom Omelette", "french", 10, ["breakfast", "lunch"], [BED, LUNCH], 1,
      [("egg", "3 eggs"), ("mushroom", "5 mushrooms"), ("butter", "1 tbsp butter"), ("cheddar", "handful of cheddar"), ("salt", "salt")],
      ["Sauté sliced mushrooms in butter; set aside.", "Pour in beaten eggs, cook until barely set.", "Add mushrooms and cheese, fold over."], 4.3),
]

out = Path(__file__).resolve().parent.parent / "public" / "data"
print(f"wrote {write_dataset(RECIPES, out)} recipes -> {out}")
